M48
; DRILL file {KiCad 7.0.9} date Fri Dec 29 18:29:18 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-29T18:29:18-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
%
G90
G05
T1
X4.725Y-2.175
X4.725Y-13.275
X18.55Y-2.2
X18.55Y-13.3
T0
M30
